---
- name: Mount the Interface file systems
  mount: 
    path: "{{ mount.path }}"
    src: "{{ mount.src }}"
    fstype: nfs
    opts: "{{ mount.option }}"
    dump: "0"
    passno: "0"
    state: mounted
  loop: "{{ mounts }}"
  loop_control:
    loop_var: mount
  when: mounts is defined and mounts
...