---
- name: Mount the Interface file systems
  mount: 
    path: "{{ item.mount_point }}"
    src: "{{ item.source }}"
    fstype: nfs
    opts: "{{ item.option }}"
    dump: "0"
    passno: "0"
    state: mounted
  loop: "{{ mounts }}"
  when: mounts is defined and mounts
...