---
sap_software_bucket: keyfile-install-media
sap_software_bucket_path: abap-nw-750-ase/

##SAP 
sid: ECD
domain_name: aws.keyfile.corp

### ASCS 
ascs_sysnr: "01"
ascs_hostname: sap-ecc-dev
scs_hostname: sap-ecc-dev

### CI
ci_sysnr: "00"
ci_hostname: sap-ecc-dev

### ASE
db_hostname: sap-ecc-dev
userstore_hostname: sap-ecc-dev 
### Passwords
master_password: Cl0ckw0rk
# master_key_password: Cl0ckw0rk
# sa_password: keyfile
# SAPSA_PASSWORD
# SAPSR3_PASSWORD
# sapsr3db_password
# SAPSSO_PASSWORD
# ssl_password
# sapadm_password
# sidadm_password
# sybsid_password
