---
- hosts: tag_app_sap
  vars_files:
    - "abap-deployment-variables.yml"
  #gather_facts: no
  tasks:
      - name: Wait for 600 seconds for connection to be available
        wait_for_connection:

  roles:
    - sap-abap-deployment
