---
- hosts: tag_app_sap:tag_app_shared-service
  # vars_files:
  #   - "variables.yml"
  #gather_facts: no
  tasks:
      - name: Wait for 600 seconds for connection to be available
        wait_for_connection:

  roles:
    - nvme-mapping
    - sap-base-build

